### ISSUE TITLE
changes to menu.  two options "OLD" and "NEW"

### ISSUE THREAD

**Issue by jir322** [Supritha-Amudhu/DOCKBlaster#16]
right now there is "DOCK options"

I would like

1. one button "Start" , which takes me to a list of all job types, among which I can choose
/jobtypes

"NEW"

2. one button "My Jobs", which takes my to a list of jobs I have run 

"OLD"

/myjobs/subsets/queued
/myjobs/subsets/finished
/myjobs/subsets/running
/myjobs?status=running
/myjobs?status=finished
/myjobs?status=crashed

**Comment by Supritha-Amudhu** [comment]
This has been implemented.
