### ISSUE TITLE
URL redirect after job submit

### ISSUE THREAD

**Issue by jir322** [Supritha-Amudhu/DOCKBlaster#48]
when we submit a job, we are taken to the results page for that job. 

Thus from /dock/cluster (submit) we are taken to  /results/139     (note job type is not part of URL)

**Comment by Supritha-Amudhu** [comment]
Issue fixed.

Commit link to the fix:
https://github.com/Supritha-Amudhu/DOCKBlaster/commit/91c15f33495dae968a39ab967e759e65e45dec7a
