### ISSUE TITLE
allow simple viewing of ascii files in browser

### ISSUE THREAD

**Issue by jir322** [Supritha-Amudhu/DOCKBlaster#53]
In a results directory such as http://blaster18.docking.org/jobresults/cluster_100 which will become http://blaster18.docking.org/results/100  

I would like it if I click on a file that is a text file, just display the file in the browser. 
We can still right- or alt-click on this file to download it.

**Comment by Supritha-Amudhu** [comment]
This issue is fixed. A user will be able to view a text file in a new browser tab or be able to download the file as well.
