### ISSUE TITLE
I have managed to break your report format

### ISSUE THREAD

**Issue by jir322** [Supritha-Amudhu/DOCKBlaster#75]
http://blaster18.docking.org/results/161

I think it might be because I created directories, not just files.  
Ideally, these should be browsable.

Thanks

**Comment by jir322** [comment]
so, it is not just sea that is broken, the results viewer is broken. I'm not sure what I did. 
Thanks

**Comment by Supritha-Amudhu** [comment]
I will take a look at this, John.

**Comment by Supritha-Amudhu** [comment]
The issue has been fixed in my local machine and pushed onto Github. I will test it out on Gimel and close the issue.

**Comment by Supritha-Amudhu** [comment]
This issue has been fixed and pulled onto Gimel.
