### ISSUE TITLE
Should we use this mechanism to communicate? 

### ISSUE THREAD

**Issue by jir322** [Supritha-Amudhu/DOCKBlaster#9]
Are you ready for comments/questions, or should I hold back while you make progress first? 

Can we agree to refer to the version running on 
http://gimel.compbio.ucsf.edu:5000/
as "gimel 5000".  By default, when I write you, I will refer to this version. 

I just tried to sign up as jir322@gmail.com on gimel 5000 
on this page after pressing REGISTER
http://gimel.compbio.ucsf.edu:5000/users/sign_up

this was the end of the stack trace. tell me if this is not useful and I will stop.

File "/mnt/nfs/work/chinzo/Projects/BlasterX_supritha/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/mnt/nfs/work/chinzo/Projects/BlasterX_supritha/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
context)
File "/mnt/nfs/work/chinzo/Projects/BlasterX_supritha/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
cursor.execute(statement, parameters)
IntegrityError: (psycopg2.IntegrityError) null value in column "user_id" violates not-null constraint DETAIL: Failing row contains (null, John, Irwin, jir322@gmail.com, pbkdf2:sha256:50000$1vcKfkiF$e66af65264d6b0307d751a0a9585add49ee..., 2018-03-01 14:54:00). [SQL: 'INSERT INTO users (first_name, last_name, email, password, date_created) VALUES (%(first_name)s, %(last_name)s, %(email)s, %(password)s, %(date_created)s) RETURNING users.user_id'] [parameters: {'last_name': u'Irwin', 'date_created': '2018-03-01 14:54', 'first_name': u'John', 'password': 'pbkdf2:sha256:50000$1vcKfkiF$e66af65264d6b0307d751a0a9585add49ee49cb845203ee85adc069bc92715ac', 'email': u'jir322@gmail.com'}] (Background on this error at: http://sqlalche.me/e/gkpj)

**Comment by Supritha-Amudhu** [comment]
Hi John, 

Please let me look into this and update you.

**Comment by jir322** [comment]
when you insert, you have null, but it should be default. also that column should be 
not null default nextval('user_id_seq'::regclass)
to set up auto increment on default insert.

**Comment by jir322** [comment]
solved
